// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnxdckwkctzuauiainii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhueGRja3drY3R6dWF1aWFpbmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjAwOTgsImV4cCI6MjA2Nzk5NjA5OH0.fcpT3tyDNAfqOsUi5x4-KP94Kzx627Gu8cI7JHc_hCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});